// server.js

import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config(); // טוען את .env

const GOOGLE_PLACES_API_KEY = process.env.GOOGLE_PLACES_API_KEY;

if (!GOOGLE_PLACES_API_KEY) {
  console.warn("⚠️ GOOGLE_PLACES_API_KEY is missing in .env");
}

const app = express();

app.use(cors());
app.use(bodyParser.json());

// 1. OpenAI client (גם לטקסט וגם ל-TTS)
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 2. קולות TTS של OpenAI
const TTS_VOICES = [
  "coral",
  "sage",
  "alloy",
  "ash",
  "ballad",
  "echo",
  "fable",
  "nova",
  "onyx",
  "shimmer",
  "verse",
];

function pickRandomVoice() {
  const idx = Math.floor(Math.random() * TTS_VOICES.length);
  const voiceName = TTS_VOICES[idx];
  const voiceIndex = idx + 1;
  const voiceKey = `OPENAI_VOICE_${voiceName.toUpperCase()}`;
  return { voiceName, voiceIndex, voiceKey };
}

// 3. TTS בעזרת OpenAI – מחזיר base64 + מידע על הקול
async function ttsWithOpenAI(text) {
  const { voiceName, voiceIndex, voiceKey } = pickRandomVoice();

  const response = await openai.audio.speech.create({
    model: "gpt-4o-mini-tts",
    voice: voiceName,
    input: text,
  });

  const buffer = Buffer.from(await response.arrayBuffer());
  const audioBase64 = buffer.toString("base64");

  const voiceId = `gpt-4o-mini-tts:${voiceName}`;

  return { audioBase64, voiceId, voiceIndex, voiceKey };
}

// 4. /api/story-both - מקבל prompt + lat/lng, מחזיר טקסט + אודיו + מידע על הקול
app.post("/api/story-both", async (req, res) => {
  try {
    const { prompt, lat, lng } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res
        .status(400)
        .json({ error: "Missing 'prompt' in request body (string required)" });
    }

    let locationLine = "Driver location is unknown.";
    if (typeof lat === "number" && typeof lng === "number") {
      locationLine = `Approximate driver location: latitude ${lat.toFixed(
        4
      )}, longitude ${lng.toFixed(4)}.`;
    }

    const systemMessage = `
אתה הקריין של אפליקציית נהיגה בשם "On The Road".

סטייל הדיבור:
- אתה מדבר כמו מספר סיפורים על הכביש: שנון, חכם, משועשע, כמו קומיקאי מצליח שיודע לרתק קהל – אבל בקול רגוע וברור שמתאים לנהג שלא יכול להתרכז רק בך.
- המטרה שלך היא לגרום לנהג לחייך, להיות מסוקרן, ולהרגיש שהוא מקבל "סוד מקומי" על המקום שהוא חולף לידו.
- השתמש במשפטים קצרים יחסית, עם פסיקים והפסקות טבעיות שמייצרות קצת מתח לפני הפאנץ', אבל בלי צעקות, בלי דרמה מוגזמת ובלי להסיח את הדעת מהכביש.
- בסוף הפסקה כדאי שיהיה פאנץ' קטן, קריצה או ניסוח מצחיק עדין, אבל שהעובדה ההיסטורית או הגאוגרפית תישאר המרכז.

חוקים קשיחים לתוכן:
- לענות תמיד בעברית בלבד, בלי משפטי פתיחה כמו "שלום" או "היי".
- להתחיל ישר בעובדת הזהב – המשפט הראשון שלך צריך כבר להכיל את הליבה המעניינת.
- לבחור עובדת זהב אחת בלבד, חזקה ומסקרנת, על מקום שנמצא כמה עשרות עד מאות מטרים ממיקום הנהג. רק אם אין ברירה, אפשר להתרחב לכל היותר עד קילומטר אחד.
- אם אין לך ביטחון בעובדה על מקום בטווח הזה, אמור במפורש שאתה מדבר באופן קצת יותר כללי על האזור הקרוב, ואל תמציא פרטים. עדיף להיות זהיר מאשר מדויק לכאורה.
- אסור לספר על מקום שנמצא בבירור מעבר לקילומטר ממיקום הנהג, ובוודאי לא על עיר אחרת כמו אשדוד או לוד אם המיקום סביב תל אביב.
- הרחב בעיקר על עובדת הזהב הזאת: מה קרה, מתי זה קרה אם ידוע, למה זה חשוב היום, ואיך זה מתחבר למה שהנהג רואה סביבו.
- אפשר להוסיף עוד פרט אחד או שניים רק אם הם מחזקים ישירות את אותה עובדה. לא להתפזר לנושאים אחרים.
- להימנע ממשפטי תיירות כלליים כמו "זו עיר תוססת ומלאת חיים". תעדיף פרטים קונקרטיים, תאריכים, אנשים, מבנים או אירועים.
- פסקה אחת זורמת, בלי נקודות רשימה, באורך בערך 80 עד 130 מילים.
`;

    const userMessage = `${locationLine}
User request: ${prompt}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [
        { role: "system", content: systemMessage },
        { role: "user", content: userMessage },
      ],
      temperature: 0.4,
    });

    const storyText = completion.choices[0]?.message?.content?.trim();
    if (!storyText) {
      throw new Error("No story generated by OpenAI");
    }

    const { audioBase64, voiceId, voiceIndex, voiceKey } =
      await ttsWithOpenAI(storyText);

    res.json({
      text: storyText,
      audioBase64,
      voiceId,
      voiceIndex,
      voiceKey,
    });
  } catch (err) {
    console.error("Error in /api/story-both:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// 5. Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok", build: "golden-fact-he-1km-style-v1" });
});

// 6. הרצה
const PORT = process.env.PORT || 3000;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`On The Road server listening on port ${PORT}`);
});

