// server.js

import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import dotenv from "dotenv";
import OpenAI from "openai";
import fetch from "node-fetch";

dotenv.config(); // טוען את .env

const app = express();

app.use(cors());
app.use(bodyParser.json());

// 1. OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 2. ElevenLabs config
const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY;

if (!ELEVENLABS_API_KEY) {
  console.error("Missing ELEVENLABS_API_KEY in environment");
  process.exit(1);
}

// טוענים את כל ה-VOICE_IDs מה-env
const VOICE_IDS = [];
for (let i = 1; i <= 10; i++) {
  const id = process.env[`ELEVENLABS_VOICE_ID_${i}`];
  if (id && id.trim() !== "") {
    VOICE_IDS.push(id.trim());
  }
}

if (VOICE_IDS.length === 0) {
  console.error("No ELEVENLABS_VOICE_ID_x defined in environment");
  process.exit(1);
}

function pickRandomVoiceId() {
  const idx = Math.floor(Math.random() * VOICE_IDS.length);
  return VOICE_IDS[idx];
}

// 3. פונקציית TTS לאילבן לאבס עם קול רנדומלי בכל קריאה
async function ttsWithElevenLabs(text) {
  const voiceId = pickRandomVoiceId();
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": ELEVENLABS_API_KEY,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      text,
      model_id: "eleven_turbo_v2",
      voice_settings: {
        stability: 0.4,
        similarity_boost: 0.8,
      },
    }),
  });

  if (!response.ok) {
    const textErr = await response.text();
    console.error("ElevenLabs error:", textErr);
    throw new Error("ElevenLabs TTS failed");
  }

  const audioBuffer = await response.arrayBuffer();
  const audioBase64 = Buffer.from(audioBuffer).toString("base64");
  return audioBase64;
}

// 4. /api/story-both - מקבל prompt, מחזיר טקסט + אודיו
app.post("/api/story-both", async (req, res) => {
  try {
    const { prompt } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res
        .status(400)
        .json({ error: "Missing 'prompt' in request body (string required)" });
    }

    const systemMessage = `
You are the narrator of a driving app called "On The Road".

You MUST follow these rules:
- Length: 60 to 90 words, no more.
- Tone: calm, clear, focused, suitable for a driver.
- Content: include at least ONE concrete, verifiable fact (for example: a year, a historical event, a known person, or a clear geographic detail).
- Use only facts that are widely known and easy to verify.
- If you are not sure about a specific fact, DO NOT invent it. Say briefly that you are not sure about the exact details and stay general.
- Do not invent legends, dialogues, or quotes.
- No more than TWO factual details in total.
- Keep it short, simple and grounded in reality.
`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [
        { role: "system", content: systemMessage },
        { role: "user", content: prompt },
      ],
      temperature: 0.3, // פחות יצירתי, יותר צמוד לעובדות
    });

    const storyText = completion.choices[0]?.message?.content?.trim();
    if (!storyText) {
      throw new Error("No story generated by OpenAI");
    }

    const audioBase64 = await ttsWithElevenLabs(storyText);

    res.json({
      text: storyText,
      audioBase64,
    });
  } catch (err) {
    console.error("Error in /api/story-both:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// 5. Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

// 6. הרצה
const PORT = process.env.PORT || 3000;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`On The Road server listening on port ${PORT}`);
});
