// server.js

import express from "express";
import cors from "cors";
import bodyParser from "body-parser";
import dotenv from "dotenv";
import OpenAI from "openai";
import fetch from "node-fetch";

dotenv.config(); // טוען את .env

const app = express();

app.use(cors());
app.use(bodyParser.json());

// 1. OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 2. ElevenLabs config
const ELEVENLABS_API_KEY = process.env.ELEVENLABS_API_KEY;

if (!ELEVENLABS_API_KEY) {
  console.error("Missing ELEVENLABS_API_KEY in environment");
  process.exit(1);
}

// טוענים את כל ה-VOICE_IDs מה-env
const VOICE_IDS = [];
for (let i = 1; i <= 10; i++) {
  const id = process.env[`ELEVENLABS_VOICE_ID_${i}`];
  if (id && id.trim() !== "") {
    VOICE_IDS.push(id.trim());
  }
}

if (VOICE_IDS.length === 0) {
  console.error("No ELEVENLABS_VOICE_ID_x defined in environment");
  process.exit(1);
}

// מחזיר גם את ה-id וגם את שם המשתנה (ELEVENLABS_VOICE_ID_3 וכו')
function pickRandomVoice() {
  const idx = Math.floor(Math.random() * VOICE_IDS.length);
  const voiceId = VOICE_IDS[idx];
  const index = idx + 1;
  const voiceKey = `ELEVENLABS_VOICE_ID_${index}`;
  return { voiceId, index, voiceKey };
}

// 3. פונקציית TTS לאילבן לאבס עם קול רנדומלי בכל קריאה
async function ttsWithElevenLabs(text) {
  const { voiceId, index, voiceKey } = pickRandomVoice();
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": ELEVENLABS_API_KEY,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      text,
      model_id: "eleven_turbo_v2",
      voice_settings: {
        stability: 0.4,
        similarity_boost: 0.8,
      },
    }),
  });

  if (!response.ok) {
    const textErr = await response.text();
    console.error("ElevenLabs error:", textErr);
    throw new Error("ElevenLabs TTS failed");
  }

  const audioBuffer = await response.arrayBuffer();
  const audioBase64 = Buffer.from(audioBuffer).toString("base64");
  return { audioBase64, voiceId, voiceIndex: index, voiceKey };
}

// 4. /api/story-both - מקבל prompt + lat/lng, מחזיר טקסט + אודיו + מידע על הקול
app.post("/api/story-both", async (req, res) => {
  try {
    const { prompt, lat, lng } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res
        .status(400)
        .json({ error: "Missing 'prompt' in request body (string required)" });
    }

    let locationLine = "Driver location is unknown.";
    if (typeof lat === "number" && typeof lng === "number") {
      locationLine = `Approximate driver location: latitude ${lat.toFixed(
        4
      )}, longitude ${lng.toFixed(4)}.`;
    }

    const systemMessage = `
You are the narrator of a driving app called "On The Road".

Hard rules:
- Length: 80 to 130 words.
- Start immediately with something interesting about the place or region - no greetings, no small talk.
- Use the given location as a hint: talk about the nearby area, or if unsure, about the wider region (for example: central Israel, the Mediterranean coast, or Israel in general).
- Include 3 to 5 concrete, widely known facts (dates, historical events, famous people, landmarks, or clear geographic features).
- Prefer to give a bit more detail on one or two "golden facts" instead of vague generalities.
- If you are not sure about local details, clearly say you are speaking about the broader region and use only safe, well-known facts.
- Do not invent legends, quotes, or hyper-specific anecdotes.
- No lists or bullet points - one flowing paragraph, short and focused.
`;

    const userMessage = `${locationLine}
User request: ${prompt}`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4.1-mini",
      messages: [
        { role: "system", content: systemMessage },
        { role: "user", content: userMessage },
      ],
      temperature: 0.35,
    });

    const storyText = completion.choices[0]?.message?.content?.trim();
    if (!storyText) {
      throw new Error("No story generated by OpenAI");
    }

    const { audioBase64, voiceId, voiceIndex, voiceKey } =
      await ttsWithElevenLabs(storyText);

    res.json({
      text: storyText,
      audioBase64,
      voiceId,
      voiceIndex,
      voiceKey, // למשל ELEVENLABS_VOICE_ID_3
    });
  } catch (err) {
    console.error("Error in /api/story-both:", err);
    res.status(500).json({ error: "Internal server error" });
  }
});

// 5. Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok", build: "short-fact-v2" });
});

// 6. הרצה
const PORT = process.env.PORT || 3000;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`On The Road server listening on port ${PORT}`);
});
